name: CD on aws 

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps: 
    - name: pull docker image 
      run: sudo docker pull arunparmal/helloazure:latest
    - name: delete the old docker container 
      run: sudo docker rm -f helloazure || true
    - name: run latest container 
      run: sudo docker run -d -p 5000:5000 --restart unless-stopped --name helloazure -t arunparmal/helloazure:latest 
